### ISSUE TITLE
symmetric? with INDArray ?

### ISSUE THREAD

**Issue by mars0i** [mikera/vectorz-clj#12]
In order to add a `symmetric?` predicate to `PMatrixPredicates` in matrix_api.clj, Mike has pointed out that I can use `.isSymmetric` in `AMatrix`, which works well. 

The `extend-protocol` for `PMatrixPredicates` also has a condition for `INDArray`.  `INDArray` doesn't have `isSymmetric()`, however.  Should it?  Under what conditions is a vectorz-clj matrix INDArray but not AMatrix?  I don't know how to test this for this case.  Should I just use a pure Clojure test in this condition? 

(Is this the place to ask these questions?  Not sure if this counts as an issue per se.)

**Comment by mikera** [comment]
Questions here are welcome (as long as they relate to an enhancement / issue to be resolved!) :-)

It's not totally clear what `symmetric?` would mean for a non-2D matrix. Hence `.isSymmetric` is only implemented for AMatrix currently (which is fine because it covers all the matrix types in Vectorz). `INDArray` is for arbitrarily-shaped arrays.

Perhaps it is a question for the numerical Clojure group (https://groups.google.com/forum/#!forum/numerical-clojure) - what should `symmetric?` return for a non-2D array? If we can answer this question, then it should be clear how to implement the protocol for `INDArray`. This would also apply to the core.matrix default.clj implementation.

My guess is that `symmetric?` should return false for anything that isn't a symmetric square 2D matrix. But someone may have a better idea.

**Comment by mikera** [comment]
Hmmm maybe the following should be equivalent:
- `(symmetric? a)`
- `(e= a (transpose a))`

In which case `symmetric?` would be true for all scalars and vectors....... and some higher dimensional arrays also

**Comment by mars0i** [comment]
In standard linear algebra, the transpose of a row vector is a column vector.  These are not, intuitively, symmetric.  Though there is only one kind of vector in core.matrix, and a vector's transpose is itself, it still seems wrong to me to say that a vector is symmetric.  I'll ask on the numerical-clojure group.

Using `e=`/`transpose` is a very simple way of testing for symmetric with 2-D matrices, though.  I wonder if it could be more efficient sometimes.  I'll have to check.

**Comment by mikera** [comment]
You can have 1xN row matrices and N*1 column matrices in core.matrix that are analogous to the row and column vectors in traditional linear algebra. In fact, it works out more logical to consider these as matrices than vectors (this means that operations like inner-product etc. become logically consistent for all dimensionalities). There's some old discussions on the mailing list about this that are worth reading: Konrad Hinsen in particular gave some great insights from his array programming experience.

While `e=` and `transpose` is interesting as a definition, I doubt it will ever be more efficient as an actual implementation approach... it is possible but that approach needs potentially more than twice as many comparisons. Also transpose is often an expensive operation, which will need to be completed before you start doing the comparisons, so you lose the opportunity to bail out early if any of the comparisons fail.

**Comment by mikera** [comment]
Closing because this is done in the latest `0.20.0` release

Semantics are exactly like `(e= a (transpose a))`
