### ISSUE TITLE
Which linear algebra algorithms need to implement

### ISSUE THREAD

**Issue by haosdent** [mikera/vectorz-clj#16]
Hi, I saw your idea "Linear Algebra for Clojure" in wiki. And I want to make sure which algorithms need to implement? SVD, QR decomposition or others? Could you give a complete list of algorithms which need to implement? Thank you very much.

**Comment by haosdent** [comment]
Do you mean port all algorithms exists in EJML to vectorz-clj?

**Comment by mikera** [comment]
I think the right strategy is to port the stuff to Vectorz - see this issue:

https://github.com/mikera/vectorz/issues/3

This will be easier, since it is just a Java -> Java port. This should also give better performance. Then it should be easy to hook this up with core.matrix protocols, so that everything is usable from Clojure.

I think the most important ones are:
- SVD
- Eigendecomposition
- LU(P)
- Cholesky
- QR
- Linear equation solving

**Comment by haosdent** [comment]
You are right. So this idea have two steps to do:
- port EMJM -> vectorz
- hook this up with core.matrix protocols in vectorz-clj

I will start to try this. Maybe would trouble you again in next days.

**Comment by mikera** [comment]
Cool, great to have you on board and doing good work on this!

Be aware that there will also need to be a couple of changes in core.matrix itself - we need to wire the protocols and API functions for the matrix decompositions

**Comment by haosdent** [comment]
Thank you for your guidance.

On Sun, Feb 16, 2014 at 9:26 PM, Mike Anderson notifications@github.comwrote:

> Cool, great to have you on board!
> 
> Be aware that there will also need to be a couple of changes in
> core.matrix itself - we need to wire the protocols and API functions for
> the matrix decompositions
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mikera/vectorz-clj/issues/16#issuecomment-35196616
> .

## 

Best Regards,
Haosdent Huang
