### ISSUE TITLE
matrix->rows->matrix round trip does not work

### ISSUE THREAD

**Issue by cheesinglee** [mikera/vectorz-clj#61]
After the update to 0.45.0, the following code throws an exception:

```
(def m (matrix/matrix :vectorz [[1 2 3][4 5 6]])
(def rows (matrix/rows m))
(def m2 (matrix/matrix :vectorz (vec rows)))
```

The exception thrown is: `java.lang.UnsupportedOperationException count not supported on this type: ArraySubVector`. A similar exception with `StridedVector` is thrown when I use `matrix/columns` instead of `matrix/rows`. 

I don't see this problem with 0.44.1 and if I remove `:vectorz` from one or both of the above `matrix/matrix` calls then it works.

**Comment by mikera** [comment]
I looked at this and it is actually a bug in `core.matrix`, due to the persistent vector implementation (note your use of `(vec rows)`). 

I have fixed this in core.matrix itself, fix will be present in the next release.

In the meantime, a workaround is to use `(matrix/coerce [] rows)` instead of `(vec rows)`.
